# Generated by Django 6.1 on 2026-09-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingchild',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='missing_children/'),
        ),
    ]
